# include "configs/train/convolutional/baseline.yaml"

model:
  hyperprior: NoisyDeepFactorized
  hyper_encoder_channels: [64]
  hyper_compressed_channels: 8
  hyper_decoder_channels: [64]
  prior_indexes_range: [16, 16, 16, 16]
  fea_num_filters: [1, 3, 3, 3, 1]
  quantize_indexes: True
