# include "configs/train/convolutional/baseline.yaml"

model:
  compressed_channels: 8
  prior_indexes_scaler: 0.0
  prior_indexes_range: [512, 512]
  quantize_indexes: True
  hyperprior: 'None'
  recurrent_part_enabled: True
  recurrent_part_channels: 64
  lossless_coord_indexes_range: [512, 512]
  lossless_fea_num_filters: [1, 3, 3, 3, 3, 1]
  hybrid_hyper_decoder_fea: True
  warmup_steps: 4000

train:
  optimizer: [AdamW, AdamW, AdamW]
  weight_decay: 0.0001
  max_grad_norm: 1.0
  learning_rate: [0.0005, 0.0003, 0.0001]
